name: CCAUD_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2023.01.10=h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.39.4
    - h5py==3.8.0
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - llvmlite==0.40.0
    - matplotlib==3.7.1
    - numba==0.57.0
    - packaging==23.1
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - six==1.16.0
    - sklearn==0.0.post5
    - threadpoolctl==3.1.0
    - torch==1.8.0+cu111
    - torchaudio==0.8.0
    - torchvision==0.9.0+cu111
    - tqdm==4.65.0
    - typing-extensions==4.6.2
    - umap-learn==0.5.3
    - zipp==3.15.0
prefix: /home/david/anaconda3/envs/CCAUD_env
